import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom'; import './index.css';

function Home() { return ( <div className="text-center p-10"> <h1 className="text-4xl font-bold mb-4">Welcome to Avila Car Rental</h1> <p className="text-lg text-gray-600">Affordable. Reliable. Convenient. Book your ride today.</p> </div> ); }

function Fleet() { const cars = [ { name: 'Tesla Model 3', description: 'Electric, modern and efficient.' }, { name: 'Kia Rio', description: 'Economical and compact for city driving.' }, { name: 'Land Rover LR2', description: 'Comfortable SUV with power and space.' } ];

return ( <div className="p-10 max-w-4xl mx-auto"> <h2 className="text-3xl font-bold mb-6 text-center">Our Fleet</h2> <div className="grid md:grid-cols-3 gap-6"> {cars.map((car, index) => ( <div key={index} className="bg-white shadow-md p-4 rounded"> <h3 className="text-xl font-semibold">{car.name}</h3> <p className="text-gray-600 mt-2">{car.description}</p> </div> ))} </div> </div> ); }

function Booking() { return ( <div className="p-10 max-w-xl mx-auto"> <h2 className="text-3xl font-bold mb-6 text-center">Book Your Car</h2> <form action="https://formspree.io/f/your-id" method="POST" className="space-y-4"> <input type="text" name="name" placeholder="Your Name" className="w-full p-3 border rounded" required /> <input type="email" name="email" placeholder="Your Email" className="w-full p-3 border rounded" required /> <input type="text" name="car" placeholder="Car Model" className="w-full p-3 border rounded" required /> <input type="date" name="pickup" className="w-full p-3 border rounded" required /> <input type="date" name="dropoff" className="w-full p-3 border rounded" required /> <button type="submit" className="bg-blue-600 text-white py-3 px-6 rounded hover:bg-blue-700 w-full">Reserve</button> </form> </div> ); }

function Contact() { return ( <div className="p-10 max-w-xl mx-auto text-center"> <h2 className="text-3xl font-bold mb-4">Contact Us</h2> <p className="text-gray-700 mb-4">Need help? Reach out on WhatsApp or email us anytime.</p> <a href="https://wa.me/13051234567" className="text-green-600 font-semibold">📱 Chat via WhatsApp</a> </div> ); }

export default function App() { return ( <Router> <nav className="bg-blue-800 text-white p-4 flex justify-between items-center"> <span className="font-bold text-lg">Avila Car Rental</span> <div className="space-x-4"> <Link to="/" className="hover:underline">Home</Link> <Link to="/fleet" className="hover:underline">Fleet</Link> <Link to="/booking" className="hover:underline">Booking</Link> <Link to="/contact" className="hover:underline">Contact</Link> </div> </nav> <Routes> <Route path="/" element={<Home />} /> <Route path="/fleet" element={<Fleet />} /> <Route path="/booking" element={<Booking />} /> <Route path="/contact" element={<Contact />} /> </Routes> <footer className="bg-gray-100 text-center py-6 text-sm text-gray-600"> © {new Date().getFullYear()} Avila Car Rental. All rights reserved. </footer> </Router> ); }

